jobs:



 - name: weekdays
   schedule: 30 7 * * 1-5 # The example will run every weekday at 7:30am.
   steps:
     - name: run models
       command: dbt run --full-refresh

 - name: weekdays_version
   schedule: 30 7 * * 1-5 # The example will run every weekday at 7:30am.
   steps:
     - name: version
       command: dbt --version
